const BASE_ENDPOINT = {
  USERS: "/api/user",
  AUTH: "/api/auth",
};

export const ENDPOINTS = {
  SCHEDULE_GET: `${BASE_ENDPOINT.USERS}/schedule`,
  SCHEDULE_CREATE: `${BASE_ENDPOINT.USERS}/schedule`,
  AUTH_LOGIN: `${BASE_ENDPOINT.AUTH}/login`,
  AUTH_REGISTER: `${BASE_ENDPOINT.AUTH}/register`,
  USER_ID_BY_USERNAME_GET: `${BASE_ENDPOINT.USERS}/search`,
  TIMESLOT_TOGGLE: `${BASE_ENDPOINT.USERS}/timeslot`,
  APPOINTMENT_SUBMIT: `${BASE_ENDPOINT.USERS}/appointment`,
};
